modLoader="javafml"
loaderVersion="${fml_version_range}"
license="GNU GPLv3"
issueTrackerURL="https://github.com/percivalalb/Trapcraft/issues"
displayURL="https://minecraft.curseforge.com/projects/trapcraft/"
logoFile="tc_logo.png"

[[mods]] #mandatory
    modId="trapcraft"
    version="${version}"
    updateJSONURL="https://www.dropbox.com/s/raw/pzo9jfvjlq1obvh/version-trapcraft.json"
    displayName="Trapcraft"
    credits="Authored By ProPercivalalb"
    authors="ProPercivalalb, Stewiecraft"
    description='''
    Addeds new blocks to create traps with, (Fan, Bear Trap, Igniter, Magnetic Chest and Grass Coverings), also a dummy. Plus upgrade your traps with special upgrades!
    '''

[[dependencies.jei]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.jei]]
    modId="minecraft" #mandatory
    mandatory=true #mandatory
    versionRange="${minecraft_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
